site_name: FUZ.zone documentation
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Quick Start: quick-start.md
  - Projects: projects.md
  - Harnesses: harnesses/index.md
  - Coverage Analysis: coverage-analysis.md
  - CI/CD Integration: ci-cd.md
  - Software Composition Analysis: sca.md
  - Pricing: pricing.md
