site_name: My Documentation
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Quick Start: quick-start.md
  - Projects: projects.md
  - Harnesses:
    - Overview: harnesses/index.md
    - Linux ELF/Shared Library: harnesses/linux.md
    - Windows EXE/DLL: harnesses/windows.md
    - Python: harnesses/python.md
    - JVM: harnesses/jvm.md
    - Rust: harnesses/rust.md
    - Embedded/Full System: harnesses/embedded.md
    - AI Harness Generation: harnesses/ai-generation.md
  - Coverage Analysis: coverage-analysis.md
  - CI/CD Integration: ci-cd.md
  - Software Composition Analysis: sca.md
  - About: about.md
